import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/ThemeProvider'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
          <Header/>
          <div className='relative w-full h-screen overflow-hidden'>
            <video src="/tissue.mp4" autoPlay muted loop
              className='absolute top-1/2 left-1/2 min-w-full min-h-full 
                -translate-x-1/2 -translate-y-1/2 z-[-1]'></video> 
          </div>   
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
