import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='h-full'>
      <body className={cn("relative h-full font-sans antialiased", inter.className)}>
        <div className='flex flex-col'>
          <main className='flex flex-col min-h-screen'>
            <NavBar/>
            <div className='flex-grow'>
              {children}
            </div>
            <div className='bg-gray-800'>
              <Footer/>
            </div>
          </main> 
        </div>
        
      </body>
    </html>
  )
}
